language: java
jdk: oraclejdk7
script:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test -B

deploy:
  provider: s3
  access_key_id:
    secure: ""
  secret_access_key:
    secure: ""
  bucket: oss.forter.com
  local-dir: /home/travis/.m2/repository/com/forter/riemann-testng-listener/
  upload-dir: repository/com/forter/riemann-testng-listener
  skip_cleanup: true
  on:
    all_branches: true
    tags: true
